# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.fuhuacn.top
date_format: "ordinal"
title: 付华的代码历程
subtitle: "学过、做过也记录过"
description: "付华的个人博客"
keywords: 付华, FU Hua, coding, fuhua, fuhuacn
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Fu Hua
organization: 
organization_url: 
github_username: fuhuacn
location: 北京
email: fuhuacn@icloud.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 博文

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /wiki/
#     label: 维基

  -
    href: /projects/
    label: 项目    

  # -
  #   href: /links/
  #   label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    projects:
        output: true
        permalink: /projects/:path/
    wiki:
        output: true
        permalink: /wiki/:path/

repository: fuhuacn/fuhuacn.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: fuhuacn
    repo: blogcomments
    oauth:
        client_id: 19ec8d59b813952d0428
        client_secret: 9509edd1fe6d69d6004892576613d43a4e816e63
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: fuhuacn
    repo: blogcomments
    clientID: 19ec8d59b813952d0428
    clientSecret: 9509edd1fe6d69d6004892576613d43a4e816e63
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-150673330-1
